/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zohaib.fraudguard;

/**
 *
 * @author zohaibakram
 */
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class individualCustomer extends javax.swing.JFrame {
    private Customer currentCustomer;
    private List<Transaction> currentTransactions;
    private List<TransactionRiskResult> currentRiskResults;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(individualCustomer.class.getName());

    /**
     * Creates new form individualCustomer
     */
    public individualCustomer() {
        initComponents();
    }
    public individualCustomer(Customer customer) {

    initComponents();
    
    currentCustomer = customer;
    
    String fullName =
        customer.getFirstName();

if (customer.getMiddleName() != null
        && !customer.getMiddleName().isBlank()) {

    fullName +=
            " " + customer.getMiddleName();
}

fullName +=
        " " + customer.getLastName();

fullNameL.setText(fullName);

    //fname.setText(customer.getFirstName());
    //mname.setText(customer.getMiddleName());
    //lname.setText(customer.getLastName());
    streetL.setText(customer.getStreet());
    cityL.setText(customer.getCity());
    stateL.setText(customer.getState());
    zipL.setText(customer.getZip());
    accountL.setText(customer.getAccountNumber());
    accountTypeL.setText(customer.getAccountType());
    phoneL.setText(customer.getPhone());
    emailL.setText(customer.getEmail());
    ssnL.setText(customer.getSsnToken());
    loadRecentTransactions(customer.getCustomerId());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        streetL = new javax.swing.JLabel();
        cityL = new javax.swing.JLabel();
        stateL = new javax.swing.JLabel();
        zipL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ssnL = new javax.swing.JLabel();
        accountL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accountTypeL = new javax.swing.JLabel();
        avaBalance = new javax.swing.JLabel();
        currBalance = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneL = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        avaBalanceL = new javax.swing.JLabel();
        currBalanceL = new javax.swing.JLabel();
        fullNameL = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        fraudrun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");
        setLocation(new java.awt.Point(230, 400));
        setMaximumSize(new java.awt.Dimension(730, 500));
        setPreferredSize(new java.awt.Dimension(730, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(730, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        streetL.setText("Street ");

        cityL.setText("City");

        stateL.setText("State");

        zipL.setText("ZIP ");

        jLabel5.setText("SSN:");

        ssnL.setText("SSn F");

        accountL.setText("Account number f");

        jLabel8.setText("Acct. Number:");

        jLabel9.setText("Acct. Type");

        accountTypeL.setText("Checking F");

        avaBalance.setText("Availble Balance:");

        currBalance.setText("Current Balance: ");

        jLabel13.setText("Phone: ");

        phoneL.setText("Phone F");

        jLabel15.setText("Email: ");

        emailL.setText("Email F");

        avaBalanceL.setText("Availble Balance:");

        currBalanceL.setText("Current Balance: ");

        fullNameL.setText("Full Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(streetL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(ssnL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cityL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(stateL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(zipL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accountL, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneL, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(emailL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(accountTypeL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(currBalance)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(currBalanceL)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(avaBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avaBalanceL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(currBalance)
                        .addComponent(currBalanceL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(accountTypeL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(avaBalance)
                                    .addComponent(avaBalanceL)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fullNameL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cityL)
                                    .addComponent(stateL)
                                    .addComponent(zipL))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ssnL))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(accountL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(phoneL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(emailL))
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Close");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Merchant", "Amount", "Timestamp", "Risk Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jButton3.setText("Transactions");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        fraudrun.setText("Run FraudGuard");
        fraudrun.addActionListener(this::fraudrunActionPerformed);

        jLabel1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Customer Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fraudrun)
                        .addGap(305, 305, 305)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(fraudrun))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fraudrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraudrunActionPerformed
        // TODO add your handling code here:
         if (currentCustomer == null) {

        JOptionPane.showMessageDialog(
                this,
                "No customer is currently loaded.",
                "FraudGuard Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    FraudAnalysisEngine engine =
            new FraudAnalysisEngine();

    currentRiskResults =
        engine.analyzeCustomerResults(
                currentCustomer.getCustomerId()
        );

    DefaultTableModel model =
            (DefaultTableModel) table1.getModel();

    /*
     * Update the Risk Rating column.
     */
    for (int row = 0; row < model.getRowCount(); row++) {

        long transactionId =
                Long.parseLong(
                        model.getValueAt(row, 0).toString()
                );

        for (TransactionRiskResult result : currentRiskResults) {

            if (result.getTransactionId() == transactionId) {

                String riskRating =
                        result.getRiskLevel()
                        + " ("
                        + result.getRiskScore()
                        + ")";

                model.setValueAt(
                        riskRating,
                        row,
                        4
                );

                break;
            }
        }
    }

    JOptionPane.showMessageDialog(
            this,
            "FraudGuard analysis completed.",
            "FraudGuard",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_fraudrunActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked

    int selectedRow =
            table1.getSelectedRow();

    if (selectedRow == -1) {
        return;
    }

    if (currentRiskResults == null) {

        JOptionPane.showMessageDialog(
                this,
                "Please run FraudGuard first.",
                "FraudGuard",
                JOptionPane.INFORMATION_MESSAGE
        );

        return;
    }

    long transactionId =
            Long.parseLong(
                    table1.getValueAt(
                            selectedRow,
                            0
                    ).toString()
            );

    Transaction selectedTransaction = null;

    for (Transaction transaction :
            currentTransactions) {

        if (transaction.getTransactionId()
                == transactionId) {

            selectedTransaction = transaction;
            break;
        }
    }

    if (selectedTransaction == null) {

        JOptionPane.showMessageDialog(
                this,
                "Transaction could not be found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    TransactionRiskResult selectedRiskResult = null;

    for (TransactionRiskResult result :
            currentRiskResults) {

        if (result.getTransactionId()
                == transactionId) {

            selectedRiskResult = result;
            break;
        }
    }

    if (selectedRiskResult == null) {

        JOptionPane.showMessageDialog(
                this,
                "FraudGuard has not analyzed this transaction yet.",
                "FraudGuard",
                JOptionPane.INFORMATION_MESSAGE
        );

        return;
    }

    Analysis analysisFrame =
            new Analysis(
                    selectedTransaction,
                    selectedRiskResult
            );

    analysisFrame.setLocationRelativeTo(this);
    analysisFrame.setVisible(true);

        
    }//GEN-LAST:event_table1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Transactions transactionsFrame =
        new Transactions(currentCustomer);

    transactionsFrame.setLocationRelativeTo(this);
    transactionsFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
        
    private void loadRecentTransactions(long customerId) {

    TransactionDAO transactionDAO =
            new TransactionDAO();

    currentTransactions =
        transactionDAO.getRecentTransactionsByCustomer(
                customerId
        );

    DefaultTableModel model =
            (DefaultTableModel) table1.getModel();

    // Clear existing rows
    model.setRowCount(0);

    // Add transactions to the table
    for (Transaction transaction : currentTransactions) {

        model.addRow(new Object[] {
            transaction.getTransactionId(),
            transaction.getMerchantName(),
            String.format(
                    "$%.2f",
                    transaction.getAmount()
            ),
            transaction.getTimestamp(),
            "Not Analyzed"
        });
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new individualCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountL;
    private javax.swing.JLabel accountTypeL;
    private javax.swing.JLabel avaBalance;
    private javax.swing.JLabel avaBalanceL;
    private javax.swing.JLabel cityL;
    private javax.swing.JLabel currBalance;
    private javax.swing.JLabel currBalanceL;
    private javax.swing.JLabel emailL;
    private javax.swing.JButton fraudrun;
    private javax.swing.JLabel fullNameL;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel phoneL;
    private javax.swing.JLabel ssnL;
    private javax.swing.JLabel stateL;
    private javax.swing.JLabel streetL;
    private javax.swing.JTable table1;
    private javax.swing.JLabel zipL;
    // End of variables declaration//GEN-END:variables
}
