/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zohaib.fraudguard;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author zohaibakram
 */
public class Transactions extends javax.swing.JFrame {
    private Customer currentCustomer;
    private List<Transaction> transactions;
    private List<TransactionRiskResult> riskResults;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Transactions.class.getName());

    /**
     * Creates new form Transactions
     */
    public Transactions() {
        initComponents();
    }
    public Transactions(Customer customer) {

    initComponents();

    currentCustomer = customer;

    fNameL.setText(
            customer.getFirstName()
            + " "
            + customer.getLastName()
    );

    accountL.setText(
            customer.getAccountNumber()
    );

    loadTransactions();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox<>();
        monthBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNameL = new javax.swing.JLabel();
        accountL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        analysisButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction History");
        setLocation(new java.awt.Point(400, 230));
        setMaximumSize(new java.awt.Dimension(730, 500));
        setMinimumSize(new java.awt.Dimension(730, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Transaction History");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jLabel3.setText("Account: ");

        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Years", "2026", "2025", "2024", "2023", "2022", "2021", "2020" }));
        yearBox.addActionListener(this::yearBoxActionPerformed);

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Months", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthBox.addActionListener(this::monthBoxActionPerformed);

        jLabel4.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jLabel4.setText("Year:");

        jLabel5.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jLabel5.setText("Month:");

        fNameL.setText("jLabel6");

        accountL.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fNameL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Merchant", "Amount", "Type", "Timestamp", "Risk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        analysisButton.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        analysisButton.setForeground(new java.awt.Color(0, 153, 0));
        analysisButton.setText("View Analysis");
        analysisButton.addActionListener(this::analysisButtonActionPerformed);

        jButton2.setFont(new java.awt.Font("Krungthep", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Close");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(analysisButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analysisButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void yearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearBoxActionPerformed
        // TODO add your handling code here:
        filterTransactions();
    }//GEN-LAST:event_yearBoxActionPerformed

    private void monthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthBoxActionPerformed
        // TODO add your handling code here:
        filterTransactions();
    }//GEN-LAST:event_monthBoxActionPerformed

    private void analysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisButtonActionPerformed
                                               
    int selectedRow = table1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a transaction first.",
                "No Transaction Selected",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Get transaction ID from the selected row
    long transactionId =
            Long.parseLong(
                    table1.getValueAt(selectedRow, 0).toString()
            );

    // Run FraudGuard analysis for this customer
    FraudAnalysisEngine engine =
            new FraudAnalysisEngine();

    riskResults =
            engine.analyzeCustomerResults(
                    currentCustomer.getCustomerId()
            );

    // Find the selected transaction
    Transaction selectedTransaction = null;

    for (Transaction transaction : transactions) {

        if (transaction.getTransactionId() == transactionId) {
            selectedTransaction = transaction;
            break;
        }
    }

    if (selectedTransaction == null) {
        JOptionPane.showMessageDialog(
                this,
                "Transaction could not be found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Find the FraudGuard result for this transaction
    TransactionRiskResult selectedRiskResult = null;

    for (TransactionRiskResult result : riskResults) {

        if (result.getTransactionId() == transactionId) {
            selectedRiskResult = result;
            break;
        }
    }

    if (selectedRiskResult == null) {
        JOptionPane.showMessageDialog(
                this,
                "FraudGuard analysis could not be found for this transaction.",
                "Analysis Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Open Analysis window
    Analysis analysisFrame =
            new Analysis(
                    selectedTransaction,
                    selectedRiskResult
            );

    analysisFrame.setLocationRelativeTo(this);
    analysisFrame.setVisible(true);

        
    }//GEN-LAST:event_analysisButtonActionPerformed
    
    private void populateYearFilter() {

    java.util.Set<Integer> years =
            new java.util.TreeSet<>(java.util.Collections.reverseOrder());

    for (Transaction transaction : transactions) {
        years.add(transaction.getTimestamp().getYear());
    }

    yearBox.removeAllItems();

    yearBox.addItem("All Years");

    for (Integer year : years) {
        yearBox.addItem(String.valueOf(year));
    }
}
    private void loadTransactions() {

    TransactionDAO transactionDAO =
            new TransactionDAO();

    transactions =
            transactionDAO.getAllTransactionsByCustomer(
                    currentCustomer.getCustomerId()
            );

    populateYearFilter();

    populateTable(transactions);
}
    private void populateTable(
        List<Transaction> transactionList) {

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
                    table1.getModel();

    model.setRowCount(0);

    for (Transaction transaction : transactionList) {

        model.addRow(new Object[] {
            transaction.getTransactionId(),

            transaction.getMerchantName(),

            String.format(
                    "$%.2f",
                    transaction.getAmount()
            ),

            transaction.getTransactionType(),

            transaction.getTimestamp(),

            "Not Analyzed"
        });
    }
}
    private void filterTransactions() {

    // Prevent filtering while the combo boxes are being populated
    if (yearBox.getSelectedItem() == null
            || monthBox.getSelectedItem() == null
            || transactions == null) {
        return;
    }

    String selectedYear =
            yearBox.getSelectedItem().toString();

    String selectedMonth =
            monthBox.getSelectedItem().toString();

    List<Transaction> filtered =
            new java.util.ArrayList<>();

    for (Transaction transaction : transactions) {

        boolean yearMatches = true;
        boolean monthMatches = true;

        // Year filter
        if (!selectedYear.equals("All Years")) {

            int transactionYear =
                    transaction.getTimestamp().getYear();

            yearMatches =
                    transactionYear
                    == Integer.parseInt(selectedYear);
        }

        // Month filter
        if (!selectedMonth.equals("All Months")) {

            int transactionMonth =
                    transaction.getTimestamp().getMonthValue();

            int selectedMonthNumber =
                    java.time.Month
                            .valueOf(
                                    selectedMonth.toUpperCase()
                            )
                            .getValue();

            monthMatches =
                    transactionMonth
                    == selectedMonthNumber;
        }

        if (yearMatches && monthMatches) {
            filtered.add(transaction);
        }
    }

    populateTable(filtered);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transactions().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountL;
    private javax.swing.JButton analysisButton;
    private javax.swing.JLabel fNameL;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JTable table1;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
